//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PSoCCreatorIdeExport {
    
    private PSoCCreatorIdeExportDevice deviceField;
    
    private PSoCCreatorIdeExportToolchain[] toolchainsField;
    
    private PSoCCreatorIdeExportProject projectField;
    
    private sbyte versionField;
    
    private bool versionFieldSpecified;
    
    /// <remarks/>
    public PSoCCreatorIdeExportDevice Device {
        get {
            return this.deviceField;
        }
        set {
            this.deviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Toolchain", IsNullable=false)]
    public PSoCCreatorIdeExportToolchain[] Toolchains {
        get {
            return this.toolchainsField;
        }
        set {
            this.toolchainsField = value;
        }
    }
    
    /// <remarks/>
    public PSoCCreatorIdeExportProject Project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VersionSpecified {
        get {
            return this.versionFieldSpecified;
        }
        set {
            this.versionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportDevice {
    
    private string partField;
    
    private string processorField;
    
    private string deviceIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Processor {
        get {
            return this.processorField;
        }
        set {
            this.processorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceID {
        get {
            return this.deviceIDField;
        }
        set {
            this.deviceIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportToolchain {
    
    private PSoCCreatorIdeExportToolchainTool[] toolField;
    
    private string nameField;
    
    private string selectedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tool")]
    public PSoCCreatorIdeExportToolchainTool[] Tool {
        get {
            return this.toolField;
        }
        set {
            this.toolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Selected {
        get {
            return this.selectedField;
        }
        set {
            this.selectedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportToolchainTool {
    
    private string nameField;
    
    private string commandField;
    
    private string optionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportProject {
    
    private string cMSIS_SVD_FileField;
    
    private string datasheetField;
    
    private PSoCCreatorIdeExportProjectLinkerFile[] linkerFilesField;
    
    private PSoCCreatorIdeExportProjectFolder[] foldersField;
    
    private string nameField;
    
    private string pathField;
    
    private string versionField;
    
    private string typeField;
    
    /// <remarks/>
    public string CMSIS_SVD_File {
        get {
            return this.cMSIS_SVD_FileField;
        }
        set {
            this.cMSIS_SVD_FileField = value;
        }
    }
    
    /// <remarks/>
    public string Datasheet {
        get {
            return this.datasheetField;
        }
        set {
            this.datasheetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LinkerFile", IsNullable=false)]
    public PSoCCreatorIdeExportProjectLinkerFile[] LinkerFiles {
        get {
            return this.linkerFilesField;
        }
        set {
            this.linkerFilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Folder", IsNullable=false)]
    public PSoCCreatorIdeExportProjectFolder[] Folders {
        get {
            return this.foldersField;
        }
        set {
            this.foldersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportProjectLinkerFile {
    
    private string toolchainField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Toolchain {
        get {
            return this.toolchainField;
        }
        set {
            this.toolchainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportProjectFolder {
    
    private PSoCCreatorIdeExportProjectFolderFiles filesField;
    
    private string buildTypeField;
    
    private string pathField;
    
    /// <remarks/>
    public PSoCCreatorIdeExportProjectFolderFiles Files {
        get {
            return this.filesField;
        }
        set {
            this.filesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BuildType {
        get {
            return this.buildTypeField;
        }
        set {
            this.buildTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportProjectFolderFiles {
    
    private PSoCCreatorIdeExportProjectFolderFilesFile[] fileField;
    
    private string[] textField;
    
    private string rootField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("File")]
    public PSoCCreatorIdeExportProjectFolderFilesFile[] File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Root {
        get {
            return this.rootField;
        }
        set {
            this.rootField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PSoCCreatorIdeExportProjectFolderFilesFile {
    
    private string buildTypeField;
    
    private string toolchainField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BuildType {
        get {
            return this.buildTypeField;
        }
        set {
            this.buildTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Toolchain {
        get {
            return this.toolchainField;
        }
        set {
            this.toolchainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
